name: TWS CI workflows

on:
    push:

jobs:
    build: 
        runs-on: ubuntu-latest # github runner (free)
        steps:
            - name: Checkout code 
              uses: actions/checkout@v4 # clonce the code ubuntu runner 
          
            - name: setup docker
              uses: docker/setup-buildx-action@v4 
